-- Tournament Auction System Database Schema
-- Run this script to create the database and tables
-- All primary keys use UNIQUEIDENTIFIER (GUID)

CREATE DATABASE Auction_Tournament
GO

USE Auction_Tournament
GO

-- 1. USERS TABLE
CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(200) NOT NULL,
    UserType NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 1. TOURNAMENTS TYPE
CREATE TABLE TournamentsTypes (
    TypeId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    UpdatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 2. TOURNAMENTS TABLE
CREATE TABLE Tournaments (
    TournamentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    TournamentAdminId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    Type UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TournamentsTypes(TypeId),
    Format NVARCHAR(50) NOT NULL,
    AuctionEnabled BIT NOT NULL DEFAULT 0,
    MinPlayers INT NOT NULL,
    MaxPlayers INT NOT NULL,
    MinBidIncrement DECIMAL(10,2) NULL,
    MaxTeamBudget DECIMAL(10,2) NULL,
    BidSeconds INT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Draft',
    CreatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    UpdatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 3. TEAMS TABLE
CREATE TABLE Teams (
    TeamId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TournamentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tournaments(TournamentId),
    TeamName NVARCHAR(100) NOT NULL,
    TeamKey NVARCHAR(50) NOT NULL UNIQUE,
    Wallet DECIMAL(10,2) NULL,
    LogoUrl VARCHAR(MAX) NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    UpdatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- PLAYERS CATEGORY
CREATE TABLE PlayersCategory (
    CategoryId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TournamentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tournaments(TournamentId),
    CategoryName NVARCHAR(100) NOT NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    UpdatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 4. PLAYERS TABLE
CREATE TABLE Players (
    PlayerId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TournamentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tournaments(TournamentId),
    Name NVARCHAR(100) NOT NULL,
    Category UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES PlayersCategory(CategoryId),
    BasePrice DECIMAL(10,2) NOT NULL,
    AssignedTeamId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Teams(TeamId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 5. AUCTION TABLE
CREATE TABLE Auction (
    AuctionId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TournamentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tournaments(TournamentId),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    StartedAt DATETIME NULL,
    EndedAt DATETIME NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    UpdatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 6. BIDS TABLE
CREATE TABLE Bids (
    BidId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    AuctionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Auction(AuctionId),
    PlayerId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId),
    TeamId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Teams(TeamId),
    BidAmount DECIMAL(10,2) NOT NULL,
    BidTime DATETIME DEFAULT GETDATE()
);
GO

-- 7. MATCHES TABLE
CREATE TABLE Matches (
    MatchId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TournamentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tournaments(TournamentId),
    TeamAId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Teams(TeamId),
    TeamBId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Teams(TeamId),
    WinningTeamId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Teams(TeamId),
    ScheduledAt DATETIME NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    CreatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    UpdatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT CK_Match_Winner CHECK (
        WinningTeamId IS NULL OR WinningTeamId IN (TeamAId, TeamBId)
    )
);
GO

-- 8. POINTS TABLE
CREATE TABLE PointsTable (
    PointId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeamId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Teams(TeamId),
    TournamentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tournaments(TournamentId),
    Points INT NOT NULL DEFAULT 0,
    GoalsScored INT NOT NULL DEFAULT 0,
    GoalsConceded INT NOT NULL DEFAULT 0,
    GoalsOrNRR DECIMAL(10,2) NULL,
    Wins INT NOT NULL DEFAULT 0,
    Losses INT NOT NULL DEFAULT 0,
    Draws INT NOT NULL DEFAULT 0,
    CreatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    UpdatedBy UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 9. SUBSCRIPTION PLANS
CREATE TABLE SubscriptionPlans (
    PlanId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PlanName NVARCHAR(100) NOT NULL,
    Price DECIMAL(10,2) NOT NULL DEFAULT 0,
    DurationInDays INT NOT NULL,
    MaxTournaments INT NULL,
    MaxTeams INT NULL,
    MaxAuctions INT NULL,
    IsActive BIT DEFAULT 1,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

-- 10. USER SUBSCRIPTIONS
CREATE TABLE UserSubscriptions (
    SubscriptionId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    PlanId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES SubscriptionPlans(PlanId),
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Active',
    AmountPaid DECIMAL(10,2) NOT NULL DEFAULT 0,
    PaymentReference NVARCHAR(200) NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO
